### ISSUE TITLE
Saint Barthélemy

### ISSUE THREAD

**Issue by Laboratory** [OpenBookPrices/country-data#52]
Hello,

Why this country has é symbol?
Usually, we have Saint Barthelemy spelling every time.

Maybe we need to improve the system and add another name.

Thx, Vitaly

**Comment by Laboratory** [comment]
And same problem has
Sao Tome and Principe <- São Tomé and Príncipe

**Comment by evdb** [comment]
Hello,

The reason the accents are there fro `Saint Barthélemy` is because they listed in the official standard. However I note that `São Tomé and Príncipe` is now `Sao Tome and Principe` so I'll update that.

The reference I'm using is: https://www.iso.org/obp/ui/#search/code/

Hope that helps, reopen if you don't agree :)
